custom = [
  "fieldworkarena.1.1.0024",
  "fieldworkarena.2.1.0075",
  "fieldworkarena.4.1.2001"
]

factory = [
  "fieldworkarena.1.1.0024",
  "fieldworkarena.1.1.0025",
  "fieldworkarena.1.1.0026",
  "fieldworkarena.1.1.0027",
  "fieldworkarena.1.1.0028",
  "fieldworkarena.1.1.0029",
  "fieldworkarena.1.1.0030",
  "fieldworkarena.1.1.0031",
  "fieldworkarena.1.1.0032",
  "fieldworkarena.2.3.0011",
  "fieldworkarena.2.3.0012",
  "fieldworkarena.2.3.0013",
  "fieldworkarena.2.3.0014",
  "fieldworkarena.2.3.0015",
  "fieldworkarena.2.3.0016",
  "fieldworkarena.2.3.0017",
  "fieldworkarena.2.3.0018",
  "fieldworkarena.2.3.0019",
  "fieldworkarena.2.3.0020",
  "fieldworkarena.2.3.0021",
  "fieldworkarena.2.3.0022",
  "fieldworkarena.2.3.0023",
  "fieldworkarena.2.3.0024",
  "fieldworkarena.2.3.0025",
  "fieldworkarena.2.3.0026",
  "fieldworkarena.2.3.0027",
  "fieldworkarena.2.3.0028",
  "fieldworkarena.2.3.0029",
  "fieldworkarena.2.3.0030",
  "fieldworkarena.2.3.0041",
  "fieldworkarena.2.3.0042",
  "fieldworkarena.2.3.0043",
  "fieldworkarena.2.3.0044",
  "fieldworkarena.2.3.0045",
  "fieldworkarena.2.3.0046",
  "fieldworkarena.2.3.0047",
  "fieldworkarena.2.3.0048",
  "fieldworkarena.2.3.0049",
  "fieldworkarena.2.3.0050",
  "fieldworkarena.2.3.0051",
  "fieldworkarena.2.3.0052",
  "fieldworkarena.2.3.0054",
  "fieldworkarena.2.3.0056",
  "fieldworkarena.2.3.0057",
  "fieldworkarena.2.3.0058",
  "fieldworkarena.2.3.0059",
  "fieldworkarena.2.3.0060",
  "fieldworkarena.2.3.0071",
  "fieldworkarena.2.3.0072",
  "fieldworkarena.2.3.0073",
  "fieldworkarena.2.3.0074",
  "fieldworkarena.2.3.0075",
  "fieldworkarena.2.3.0076",
  "fieldworkarena.2.3.0083",
  "fieldworkarena.2.3.0084",
  "fieldworkarena.2.3.0085",
  "fieldworkarena.2.3.0086",
  "fieldworkarena.2.3.0087",
  "fieldworkarena.2.3.0088",
  "fieldworkarena.2.3.0089",
  "fieldworkarena.2.3.0090",
  "fieldworkarena.2.3.0091",
  "fieldworkarena.2.3.0092",
  "fieldworkarena.3.3.0003",
  "fieldworkarena.3.3.0004",
  "fieldworkarena.3.3.0005",
  "fieldworkarena.3.3.0007",
  "fieldworkarena.3.4.0003",
  "fieldworkarena.3.4.0004",
  "fieldworkarena.3.4.0005",
  "fieldworkarena.3.4.0007",
  "fieldworkarena.4.2.0001",
  "fieldworkarena.4.2.0002",
  "fieldworkarena.4.2.0003",
  "fieldworkarena.4.2.0004",
  "fieldworkarena.4.2.0005",
  "fieldworkarena.4.2.0026",
  "fieldworkarena.4.2.0028",
  "fieldworkarena.4.2.0030",
]

warehouse = [
  "fieldworkarena.1.1.0033",
  "fieldworkarena.1.1.0034",
  "fieldworkarena.1.1.0035",
  "fieldworkarena.1.1.0036",
  "fieldworkarena.1.1.0037",
  "fieldworkarena.1.1.0038",
  "fieldworkarena.1.1.0039",
  "fieldworkarena.1.1.0040",
  "fieldworkarena.1.1.0041",
  "fieldworkarena.1.1.0042",
  "fieldworkarena.1.1.0043",
  "fieldworkarena.2.1.0001",
  "fieldworkarena.2.1.0002",
  "fieldworkarena.2.1.0003",
  "fieldworkarena.2.1.0004",
  "fieldworkarena.2.1.0005",
  "fieldworkarena.2.1.0006",
  "fieldworkarena.2.1.0007",
  "fieldworkarena.2.1.0008",
  "fieldworkarena.2.1.0009",
  "fieldworkarena.2.1.0010",
  "fieldworkarena.2.1.0011",
  "fieldworkarena.2.1.0012",
  "fieldworkarena.2.1.0013",
  "fieldworkarena.2.1.0014",
  "fieldworkarena.2.1.0015",
  "fieldworkarena.2.1.0016",
  "fieldworkarena.2.1.0017",
  "fieldworkarena.2.1.0018",
  "fieldworkarena.2.1.0019",
  "fieldworkarena.2.1.0020",
  "fieldworkarena.2.1.0021",
  "fieldworkarena.2.1.0022",
  "fieldworkarena.2.1.0023",
  "fieldworkarena.2.1.0024",
  "fieldworkarena.2.1.0025",
  "fieldworkarena.2.1.0051",
  "fieldworkarena.2.1.0052",
  "fieldworkarena.2.1.0053",
  "fieldworkarena.2.1.0054",
  "fieldworkarena.2.1.0055",
  "fieldworkarena.2.1.0056",
  "fieldworkarena.2.1.0057",
  "fieldworkarena.2.1.0058",
  "fieldworkarena.2.1.0059",
  "fieldworkarena.2.1.0060",
  "fieldworkarena.2.1.0061",
  "fieldworkarena.2.1.0062",
  "fieldworkarena.2.1.0063",
  "fieldworkarena.2.1.0064",
  "fieldworkarena.2.1.0065",
  "fieldworkarena.2.1.0066",
  "fieldworkarena.2.1.0067",
  "fieldworkarena.2.1.0068",
  "fieldworkarena.2.1.0069",
  "fieldworkarena.2.1.0070",
  "fieldworkarena.2.1.0071",
  "fieldworkarena.2.1.0072",
  "fieldworkarena.2.1.0073",
  "fieldworkarena.2.1.0074",
  "fieldworkarena.2.1.0075",
  "fieldworkarena.2.2.0001",
  "fieldworkarena.2.2.0002",
  "fieldworkarena.2.2.0003",
  "fieldworkarena.2.2.0004",
  "fieldworkarena.2.2.0005",
  "fieldworkarena.2.2.0006",
  "fieldworkarena.2.2.0007",
  "fieldworkarena.2.2.0008",
  "fieldworkarena.2.2.0009",
  "fieldworkarena.2.2.0010",
  "fieldworkarena.2.2.0011",
  "fieldworkarena.2.2.0012",
  "fieldworkarena.2.2.0013",
  "fieldworkarena.2.2.0014",
  "fieldworkarena.2.2.0015",
  "fieldworkarena.2.2.0017",
  "fieldworkarena.2.2.0018",
  "fieldworkarena.2.2.0019",
  "fieldworkarena.2.2.0020",
  "fieldworkarena.2.2.0021",
  "fieldworkarena.2.2.0022",
  "fieldworkarena.2.2.0023",
  "fieldworkarena.2.2.0024",
  "fieldworkarena.2.2.0025",
  "fieldworkarena.2.2.0046",
  "fieldworkarena.2.2.0047",
  "fieldworkarena.2.2.0048",
  "fieldworkarena.2.2.0050",
  "fieldworkarena.2.2.0051",
  "fieldworkarena.2.2.0052",
  "fieldworkarena.2.2.0053",
  "fieldworkarena.2.2.0055",
  "fieldworkarena.2.2.0056",
  "fieldworkarena.2.2.0057",
  "fieldworkarena.2.2.0058",
  "fieldworkarena.2.2.0059",
  "fieldworkarena.2.2.0060",
  "fieldworkarena.2.2.0061",
  "fieldworkarena.2.2.0062",
  "fieldworkarena.2.2.0063",
  "fieldworkarena.2.2.0064",
  "fieldworkarena.2.2.0065",
  "fieldworkarena.2.2.0066",
  "fieldworkarena.2.2.0067",
  "fieldworkarena.2.2.0068",
  "fieldworkarena.2.2.0069",
  "fieldworkarena.2.2.0070",
  "fieldworkarena.2.2.0071",
  "fieldworkarena.2.2.0072",
  "fieldworkarena.2.2.0073",
  "fieldworkarena.2.2.0074",
  "fieldworkarena.2.2.0075",
  "fieldworkarena.2.2.0076",
  "fieldworkarena.2.2.0077",
  "fieldworkarena.2.2.0078",
  "fieldworkarena.2.2.0079",
  "fieldworkarena.2.2.0080",
  "fieldworkarena.2.2.0081",
  "fieldworkarena.2.2.0082",
  "fieldworkarena.2.2.0083",
  "fieldworkarena.2.2.0084",
  "fieldworkarena.2.2.0085",
  "fieldworkarena.2.2.0086",
  "fieldworkarena.2.2.0087",
  "fieldworkarena.2.2.0088",
  "fieldworkarena.2.2.0089",
  "fieldworkarena.2.2.0090",
  "fieldworkarena.2.2.0091",
  "fieldworkarena.2.2.0092",
  "fieldworkarena.2.2.0095",
  "fieldworkarena.2.2.0096",
  "fieldworkarena.2.2.0097",
  "fieldworkarena.2.2.0098",
  "fieldworkarena.2.2.0099",
  "fieldworkarena.2.2.0100",
  "fieldworkarena.2.2.0102",
  "fieldworkarena.2.2.0103",
  "fieldworkarena.2.2.0104",
  "fieldworkarena.2.2.0105",
  "fieldworkarena.2.2.0106",
  "fieldworkarena.2.2.0107",
  "fieldworkarena.2.2.0108",
  "fieldworkarena.2.2.0109",
  "fieldworkarena.2.2.0110",
  "fieldworkarena.2.2.0111",
  "fieldworkarena.2.2.0112",
  "fieldworkarena.2.2.0113",
  "fieldworkarena.2.2.0114",
  "fieldworkarena.2.2.0115",
  "fieldworkarena.3.1.0004",
  "fieldworkarena.3.1.0013",
  "fieldworkarena.3.2.0004",
  "fieldworkarena.4.1.0035",
  "fieldworkarena.4.1.0036",
  "fieldworkarena.4.1.0037",
  "fieldworkarena.4.1.0038",
  "fieldworkarena.4.1.0039",
  "fieldworkarena.4.1.0040",
  "fieldworkarena.4.1.0041",
  "fieldworkarena.4.1.0042",
  "fieldworkarena.4.1.0044",
]

retail = [
  "fieldworkarena.4.1.2001",
  "fieldworkarena.4.1.2002",
  "fieldworkarena.4.1.2003",
  "fieldworkarena.4.1.2004",
  "fieldworkarena.4.1.2005",
]
